Repository Yoast/developer, pull requests merged in 2024-02, with the labels that each got.

#281 Add condition to suffix rendering
  src/plugins/changelog/theme/ChangelogList/index.tsx
Labels: enhancement

#282 Introduce linting to developer repository
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/components/YoastSchemaExample/index.js
  src/plugins/changelog/index.js
  src/theme/BlogPostPage/Metadata/index.js
  src/theme/BlogSidebar/Desktop/index.js
  src/theme/BlogSidebar/Mobile/index.js
  src/theme/BlogSidebar/index.js
  src/theme/DocItem/Metadata/index.js
  tsconfig.json
  yarn.lock
Labels: enhancement, Dev acceptance

#275 Adds documentation about new urlset filter.
  docs/features/xml-sitemaps/api.md
Labels: documentation
